language: en

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: DIETClassifier
  epochs: 10
  scale_loss: False
  weight_sparsity: 0.3
  transformer_size: 32
  BILOU_flag: True
- name: ResponseSelector
  epochs: 1
- name: EntitySynonymMapper

policies:
- name: RulePolicy
#- name: TEDPolicy
#  max_history: 5
#  batch_strategy: balanced
#  epochs: 1
#  random_seed: 666
#  evaluate_on_num_examples: 0
